# Generated by Django 5.1.6 on 2025-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
